### ISSUE TITLE
details tab

### ISSUE THREAD

**Issue by rkgdgames** [jlnordin/LiveBlueprintVariableDebugging#1]
Hi, thanks for the plugin, do you know a way to keep details selected on a actor while playing? Eject from player to debug its not a great solution for me.
I wish I could play with my character and interact with world and see the results without eject.

**Comment by jlnordin** [comment]
Seems like a good feature. I'll look into this and see how feasible it is.

**Comment by jlnordin** [comment]
Version 1.1 now has a new setting to keep the actor selected when playing or simulating.

Checkout the releases section or the commit at dfe7d295e91ab472206cd824b62dd75fdb14dc58. Update to the Marketplace version has been submitted.
